#!/bin/bash

PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
CURRENT_DIR="`pwd`"
cd "`dirname \"$PRG\"`"/../../ >/dev/null
ROOTDIR="`pwd -P`"
cd "$CURRENT_DIR" >/dev/null

source "${CURRENT_DIR}/common"

run register_certificate "${CURRENT_DIR}/fixture/conf/initializer.properties"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "Initialize" \
  "com.scalar.ist.function.Initialize" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/Initialize.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "RegisterCompany" \
  "com.scalar.ist.function.RegisterCompany" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/RegisterCompany.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "RegisterOrganization" \
  "com.scalar.ist.function.RegisterOrganization" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/RegisterOrganization.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpdateCompany" \
  "com.scalar.ist.function.UpdateCompany" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpdateCompany.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpsertOrganization" \
  "com.scalar.ist.function.UpsertOrganization" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpsertOrganization.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpsertUserProfile" \
  "com.scalar.ist.function.UpsertUserProfile" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpsertUserProfile.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "RegisterThirdParty" \
  "com.scalar.ist.function.RegisterThirdParty" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/RegisterThirdParty.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpdateThirdParty" \
  "com.scalar.ist.function.UpdateThirdParty" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpdateThirdParty.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "RegisterConsentStatement" \
  "com.scalar.ist.function.RegisterConsentStatement" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/RegisterConsentStatement.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpdateConsentStatementVersion" \
  "com.scalar.ist.function.UpdateConsentStatementVersion" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpdateConsentStatementVersion.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpdateConsentStatementRevision" \
  "com.scalar.ist.function.UpdateConsentStatementRevision" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpdateConsentStatementRevision.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpdateConsentStatementStatus" \
  "com.scalar.ist.function.UpdateConsentStatementStatus" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpdateConsentStatementStatus.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpsertMaster" \
  "com.scalar.ist.function.UpsertMaster" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpsertMaster.class"

run register_function "${CURRENT_DIR}/fixture/conf/initializer.properties" \
  "UpsertConsentStatus" \
  "com.scalar.ist.function.UpsertConsentStatus" \
  "${ROOTDIR}/contracts_and_functions/build/classes/java/main/com/scalar/ist/function/UpsertConsentStatus.class"
