#!/bin/bash

PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
CURRENT_DIR="`pwd`"
cd "`dirname \"$PRG\"`"/../../ >/dev/null
ROOTDIR="`pwd -P`"
cd "$CURRENT_DIR" >/dev/null

source "${CURRENT_DIR}/common.sh"
source "${CURRENT_DIR}/fixture/argument/upsert_consent_status_register"

run register_certificate "${CURRENT_DIR}/fixture/conf/data_subject.properties"

run register_contracts "${CURRENT_DIR}/fixture/conf/data_subject.properties" \
  "${CURRENT_DIR}/fixture/conf/upsert_consent_status_register.toml"

run execute_contract "${CURRENT_DIR}/fixture/conf/data_subject.properties" \
  "UpsertConsentStatus" \
  "UPSERT_CONSENT_STATUS_ARG"

exit ${TEST_STATUS}
