#!/bin/bash

PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
CURRENT_DIR="`pwd`"
cd "`dirname \"$PRG\"`"/../../ >/dev/null
ROOTDIR="`pwd -P`"
cd "$CURRENT_DIR" >/dev/null

source "${CURRENT_DIR}/common.sh"
source "${CURRENT_DIR}/fixture/argument/upsert_user_profile_controller"

run register_certificate "${CURRENT_DIR}/fixture/conf/admin.properties"

run register_contracts "${CURRENT_DIR}/fixture/conf/admin.properties" \
  "${CURRENT_DIR}/fixture/conf/upsert_user_profile_controller.toml"

run execute_contract "${CURRENT_DIR}/fixture/conf/admin.properties" \
  "UpsertUserProfile" \
  "UPSERT_USER_PROFILE_CONTROLLER_ARG"

exit ${TEST_STATUS}
