[[contracts]]
contract-id = "GetAssetRecord"
contract-binary-name = "com.scalar.ist.contract.GetAssetRecord"
contract-class-file = "./contract/GetAssetRecord.class"
[[contracts]]
contract-id = "ValidateArgument"
contract-binary-name = "com.scalar.ist.contract.ValidateArgument"
contract-class-file = "./contract/ValidateArgument.class"
[[contracts]]
contract-id = "ValidatePermission"
contract-binary-name = "com.scalar.ist.contract.ValidatePermission"
contract-class-file = "./contract/ValidatePermission.class"
[[contracts]]
contract-id = "GetConsentStatus"
contract-binary-name = "com.scalar.ist.contract.GetConsentStatus"
contract-class-file = "./contract/GetConsentStatus.class"
[[contracts]]
contract-id = "PutAssetRecord"
contract-binary-name = "com.scalar.ist.contract.PutAssetRecord"
contract-class-file = "./contract/PutAssetRecord.class"
[[contracts]]
contract-id = "Initialize"
contract-binary-name = "com.scalar.ist.contract.Initialize"
contract-class-file = "./contract/Initialize.class"
[[contracts]]
contract-id = "GetUserProfile"
contract-binary-name = "com.scalar.ist.contract.GetUserProfile"
contract-class-file = "./contract/GetUserProfile.class"
[[contracts]]
contract-id = "RegisterCompany"
contract-binary-name = "com.scalar.ist.contract.RegisterCompany"
contract-class-file = "./contract/RegisterCompany.class"
[[contracts]]
contract-id = "RegisterConsentStatement"
contract-binary-name = "com.scalar.ist.contract.RegisterConsentStatement"
contract-class-file = "./contract/RegisterConsentStatement.class"
[[contracts]]
contract-id = "RegisterThirdParty"
contract-binary-name = "com.scalar.ist.contract.RegisterThirdParty"
contract-class-file = "./contract/RegisterThirdParty.class"
[[contracts]]
contract-id = "UpdateCompany"
contract-binary-name = "com.scalar.ist.contract.UpdateCompany"
contract-class-file = "./contract/UpdateCompany.class"
[[contracts]]
contract-id = "UpdateConsentStatementRevision"
contract-binary-name = "com.scalar.ist.contract.UpdateConsentStatementRevision"
contract-class-file = "./contract/UpdateConsentStatementRevision.class"
[[contracts]]
contract-id = "UpdateConsentStatementStatus"
contract-binary-name = "com.scalar.ist.contract.UpdateConsentStatementStatus"
contract-class-file = "./contract/UpdateConsentStatementStatus.class"
[[contracts]]
contract-id = "UpdateConsentStatementVersion"
contract-binary-name = "com.scalar.ist.contract.UpdateConsentStatementVersion"
contract-class-file = "./contract/UpdateConsentStatementVersion.class"
[[contracts]]
contract-id = "UpdateThirdParty"
contract-binary-name = "com.scalar.ist.contract.UpdateThirdParty"
contract-class-file = "./contract/UpdateThirdParty.class"
[[contracts]]
contract-id = "UpsertConsentStatus"
contract-binary-name = "com.scalar.ist.contract.UpsertConsentStatus"
contract-class-file = "./contract/UpsertConsentStatus.class"
[[contracts]]
contract-id = "UpsertOrganization"
contract-binary-name = "com.scalar.ist.contract.UpsertOrganization"
contract-class-file = "./contract/UpsertOrganization.class"
[[contracts]]
contract-id = "UpsertUserProfile"
contract-binary-name = "com.scalar.ist.contract.UpsertUserProfile"
contract-class-file = "./contract/UpsertUserProfile.class"
[[contracts]]
contract-id = "RegisterBenefit"
contract-binary-name = "com.scalar.ist.contract.UpsertMaster"
contract-class-file = "./contract/UpsertMaster.class"
[[contracts]]
contract-id = "RegisterDataRetentionPolicy"
contract-binary-name = "com.scalar.ist.contract.UpsertMaster"
contract-class-file = "./contract/UpsertMaster.class"
[[contracts]]
contract-id = "RegisterDataSetSchema"
contract-binary-name = "com.scalar.ist.contract.UpsertMaster"
contract-class-file = "./contract/UpsertMaster.class"
[[contracts]]
contract-id = "RegisterPurpose"
contract-binary-name = "com.scalar.ist.contract.UpsertMaster"
contract-class-file = "./contract/UpsertMaster.class"
[[contracts]]
contract-id = "UpdateDataRetentionPolicy"
contract-binary-name = "com.scalar.ist.contract.UpsertMaster"
contract-class-file = "./contract/UpsertMaster.class"
[[contracts]]
contract-id = "UpdateDataSetSchema"
contract-binary-name = "com.scalar.ist.contract.UpsertMaster"
contract-class-file = "./contract/UpsertMaster.class"
[[contracts]]
contract-id = "UpdatePurpose"
contract-binary-name = "com.scalar.ist.contract.UpsertMaster"
contract-class-file = "./contract/UpsertMaster.class"
[[contracts]]
contract-id = "UpdateBenefit"
contract-binary-name = "com.scalar.ist.contract.UpsertMaster"
contract-class-file = "./contract/UpsertMaster.class"
