cd ../tools/deploy
./functions
./initialize
./register_company
./upsert_user_profile_admin
./upsert_user_profile_controller
./register_purpose
./update_purpose
./register_data_set_schema
./update_data_set_schema
./register_third_party
./update_third_party
./register_data_retention_policy
./update_data_retention_policy
./register_benefit
./update_benefit
./register_consent_statement
./update_consent_statement_revision
./update_consent_statement_version
./update_consent_statement_status
./get_consent_statement_history
./update_company
./upsert_user_profile_controller_add_processor
./upsert_organization
./upsert_consent_status_register
./upsert_consent_status_update
./get_consent_status_data_subject
./get_consent_status_controller
