#!/bin/bash
#
# This script provides commands to start, stop and check the status of the Cassandra database
usage="$(basename "$0") [-h] {up|down|is_up} -- program to manage the IST Cassandra database

  ARGUMENTS:
    up      start the Cassandra docker container
    down    stop the Cassandra docker container
    is_up   return the starting status of Cassandra : (true|false)

  OPTIONS:
    -h      print the usage"

readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
readonly CONTAINER_NAME=ist.cassandra

case "$1" in
up)
  docker-compose -f "${BASEDIR}/docker-compose.yml" up -d
  echo -n 'Wait for C* '
  until docker exec "${CONTAINER_NAME}" cqlsh 2>/dev/null; do
    sleep 0.5
    echo -n '#'
  done
  echo ""
  docker exec "${CONTAINER_NAME}" cqlsh -f /schema.cql
  ;;
down)
  docker-compose -f "${BASEDIR}/docker-compose.yml" down -v
  ;;
is_up)
  RUNNING_STATUS=$(docker ps -f status=running -f "name=${CONTAINER_NAME}" --format '{{.Status}}')
  if [[ -n "$RUNNING_STATUS" ]]; then
    echo 'true'
  else
    echo 'false'
  fi
  ;;
'' | -h)
  echo "${usage}"
  ;;
*)
  echo "Unexpected goal ${1}"
  printf '\n'
  echo "${usage}"
  ;;
esac
