name: CI

on:
  push
#  pull_request:
#    branches:
#      - master
#      - '*'

jobs:
  scalar-ist-ci-tests:

    runs-on: ubuntu-18.04
    env:
      CONTRACTS_AND_FUNCTIONS_DIR: ${{ github.workspace }}/contracts_and_functions

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests
        run: |
          cd ${{ env.CONTRACTS_AND_FUNCTIONS_DIR }}
          ./gradlew test

      - name: Build scalar-ist contracts and functions
        run: |
          cd ${{ env.CONTRACTS_AND_FUNCTIONS_DIR }}
          ./gradlew build
