name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Create containers
        run: gradle docker

      - name: Push containers
        run: |
          docker push ghcr.io/scalar-labs/scalar-ist-loader:${{ steps.version.outputs.version }}
